name: Versioning & deploy

on:
    pull_request_target:       
        branches:
            - master
        types:
            - closed       
jobs:
    version:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        outputs:
          NEW_TAG: ${{ steps.version.outputs.version }}
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: config user
            run: |
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config user.name "github-actions[bot]"

          - name: Version
            uses: paulhatch/semantic-version@v5.3.0
            id: version
            with:
              tag_prefix: "v"
              major_pattern: "(MAJOR)"
              minor_pattern: "(MINOR)"
         
          - name: Add tag
            run: |
              echo "$NEW_TAG"
              git tag -a $NEW_TAG -m "new version $NEW_TAG"
              git push origin $NEW_TAG
            env:
              NEW_TAG: v${{ steps.version.outputs.version }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              NEW_TAG: v${{ steps.version.outputs.version }}
            with:
              tag_name: ${{ env.NEW_TAG }}
              release_name: ${{ env.NEW_TAG }}
              body: |
                release create from actions
    build:
      needs: version
      runs-on: ubuntu-latest
      env:
        NEW_TAG: ${{ needs.version.outputs.NEW_TAG }}
      steps:
        - uses: actions/checkout@v4
          with:
            ref: v${{ needs.version.outputs.NEW_TAG }}
        - run: echo "new tag - $NEW_TAG"
        - uses: jossef/action-set-json-field@v2.1
          with:
            file: package.json
            field: version
            value: ${{ env.NEW_TAG }}
        - run: cat package.json
        - uses: actions/setup-node@v3
          with:
            node-version: '18.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}